services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
  api:
    image: api/image
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static_volume:/example/staticfiles
    depends_on:
      db:
        condition: service_healthy
