services:
  nginx:
    build:
      context: ../
      dockerfile: ./common/build/proxy.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/api/staticfiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
